In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import sklearn as skl

In [6]:
data = pd.read_csv('C:/Udemy_learnings/Absenteeism-data.csv')
data.head()

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2

In [8]:
df= data.copy()

In [11]:
abs_data =df.drop('ID',axis=1)

In [14]:
abs_data['Reason for Absence'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16], dtype=int64)

In [16]:
sorted(abs_data['Reason for Absence'].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28]

In [18]:
reason_dummies = pd.get_dummies(abs_data['Reason for Absence'])

In [20]:
reason_dummies

,0,1,2,3,4,5,6,7,8,9,...,18,19,21,22,23,24,25,26,27,28
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
10,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
24,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
28,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
671,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
672,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
673,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
674,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
675,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
676,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
677,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
678,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
679,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
680,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
681,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
682,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
683,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
684,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
685,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
686,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
687,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
688,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
689,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
690,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
691,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
692,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
693,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
694,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
695,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
696,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
697,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
698,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
699,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [92]:
age_dummies=pd.get_dummies(abs_data['Age'],drop_first=True)

In [93]:
age_dummies

,28,29,30,31,32,33,34,36,37,38,39,40,41,43,46,47,48,49,50,58
0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
6,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
20,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
22,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
25,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
27,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
671,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
672,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
673,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
674,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
675,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
676,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
677,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
678,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
679,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
680,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
681,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
682,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
683,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
684,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
685,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
686,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
687,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
688,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
689,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
690,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
691,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
692,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
693,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
694,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
695,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
696,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
697,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
698,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
699,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0

In [30]:
age_dummies['check']=age_dummies.sum(axis=1)
#age_dummies

In [33]:
age_dummies['check'].unique()

array([1], dtype=int64)

In [36]:
age_dummies.drop(27,axis=1)

,28,29,30,31,32,33,34,36,37,38,...,40,41,43,46,47,48,49,50,58,check
0,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
2,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
5,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
6,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
8,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
10,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
11,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
12,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
13,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
14,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
15,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
16,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
17,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
18,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
20,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
21,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
22,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
23,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
24,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
25,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
26,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
27,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
28,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
29,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
671,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
672,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
673,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
674,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
675,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
676,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
677,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
678,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
679,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
680,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
681,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
682,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
683,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
684,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
685,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
686,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
687,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
688,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
689,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
690,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
691,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
692,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
693,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
694,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
695,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
696,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
697,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
698,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
699,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1

In [91]:
age_dummies.drop('check',axis=1)

,27,28,29,30,31,32,33,34,36,37,...,39,40,41,43,46,47,48,49,50,58
0,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
20,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
671,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
672,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
673,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
674,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
675,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
676,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
677,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
678,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
679,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
680,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
681,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
682,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
683,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
684,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
685,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
686,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
687,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
688,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
689,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
690,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
691,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
692,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
693,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
694,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
695,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
696,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
697,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
698,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
699,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [96]:
#age_dummies
df_no_age=abs_data.drop('Age',axis=1)

In [39]:
sorted(abs_data['Age'].unique())

[27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 36,
 37,
 38,
 39,
 40,
 41,
 43,
 46,
 47,
 48,
 49,
 50,
 58]

In [41]:
reason_dummies=pd.get_dummies(abs_data['Reason for Absence'],drop_first=True)

In [43]:
reason_dummies

,1,2,3,4,5,6,7,8,9,10,...,18,19,21,22,23,24,25,26,27,28
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
10,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
24,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
28,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
671,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
672,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
673,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
674,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
675,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
676,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
677,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
678,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
679,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
680,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
681,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
682,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
683,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
684,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
685,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
686,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
687,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
688,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
689,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
690,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
691,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
692,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
693,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
694,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
695,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
696,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
697,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
698,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
699,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [45]:
abs_data.columns.values

array(['Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours'], dtype=object)

In [48]:
abs_data=abs_data.drop('Reason for Absence',axis=1)

In [50]:
abs_data

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,23/07/2015,289,36,33,239.554,30,1,2,1,2
5,10/07/2015,179,51,38,239.554,31,1,0,0,2
6,17/07/2015,361,52,28,239.554,27,1,1,4,8
7,24/07/2015,260,50,36,239.554,23,1,4,0,4
8,06/07/2015,155,12,34,239.554,25,1,2,0,40
9,13/07/2015,235,11,37,239.554,29,3,1,1,8
10,20/07/2015,260,50,36,239.554,23,1,4,0,8
11,14/07/2015,260,50,36,239.554,23,1,4,0,8
12,15/07/2015,260,50,36,239.554,23,1,4,0,8
13,15/07/2015,179,51,38,239.554,31,1,0,0,1
14,15/07/2015,179,51,38,239.554,31,1,0,0,4
15,17/07/2015,246,25,41,239.554,23,1,0,0,8
16,17/07/2015,179,51,38,239.554,31,1,0,0,2
17,27/07/2015,179,51,38,239.554,31,1,0,0,8
18,30/07/2015,189,29,33,239.554,25,1,2,2,8
19,05/08/2015,248,25,47,205.917,32,1,2,1,2
20,12/08/2015,330,16,28,205.917,25,2,0,0,8
21,03/08/2015,179,51,38,205.917,31,1,0,0,1
22,10/08/2015,361,52,28,205.917,27,1,1,4,40
23,14/08/2015,260,50,36,205.917,23,1,4,0,4
24,17/08/2015,289,36,33,205.917,30,1,2,1,8
25,24/08/2015,361,52,28,205.917,27,1,1,4,7
26,04/08/2015,289,36,33,205.917,30,1,2,1,1
27,12/08/2015,157,27,29,205.917,22,1,0,0,4
28,19/08/2015,289,36,33,205.917,30,1,2,1,8
29,28/08/2015,179,51,38,205.917,31,1,0,0,2
...,...,...,...,...,...,...,...,...,...,...
670,24/04/2018,155,12,34,246.288,25,1,2,0,4
671,26/04/2018,225,26,28,246.288,24,1,1,2,8
672,26/04/2018,118,13,50,246.288,31,1,1,0,2
673,27/04/2018,179,26,30,246.288,19,3,0,0,2
674,07/05/2018,235,11,37,237.656,29,3,1,1,8
675,09/05/2018,225,15,41,237.656,28,4,2,2,3
676,09/05/2018,235,16,32,237.656,25,3,0,0,2
677,09/05/2018,118,10,37,237.656,28,1,0,0,3
678,09/05/2018,235,20,43,237.656,38,1,1,0,8
679,10/05/2018,179,26,30,237.656,19,3,0,0,1
680,10/05/2018,291,31,40,237.656,25,1,1,1,2
681,10/05/2018,225,15,41,237.656,28,4,2,2,8
682,11/05/2018,300,26,43,237.656,25,1,2,1,64
683,11/05/2018,225,15,41,237.656,28,4,2,2,8
684,11/05/2018,179,26,30,237.656,19,3,0,0,2
685,14/05/2018,118,13,50,237.656,31,1,1,0,2
686,15/05/2018,118,13,50,237.656,31,1,1,0,3
687,15/05/2018,118,10,37,237.656,28,1,0,0,1
688,15/05/2018,118,13,50,237.656,31,1,1,0,0
689,16/05/2018,179,26,30,237.656,19,3,0,0,2
690,16/05/2018,378,49,36,237.656,21,1,2,4,0
691,18/05/2018,179,22,40,237.656,22,2,2,0,1
692,21/05/2018,155,12,34,237.656,25,1,2,0,48
693,21/05/2018,235,16,32,237.656,25,3,0,0,8
694,23/05/2018,291,31,40,237.656,25,1,1,1,8
695,23/05/2018,179,22,40,237.656,22,2,2,0,8
696,23/05/2018,225,26,28,237.656,24,1,1,2,3
697,24/05/2018,330,16,28,237.656,25,2,0,0,8
698,24/05/2018,235,16,32,237.656,25,3,0,0,2
699,31/05/2018,291,31,40,237.656,25,1,1,1,2

In [54]:
reason_dummies.loc[:,1:14].max(axis=1)

0      0
1      0
2      0
3      1
4      0
5      0
6      0
7      0
8      0
9      0
10     1
11     1
12     1
13     1
14     0
15     1
16     0
17     0
18     1
19     0
20     1
21     1
22     1
23     0
24     0
25     0
26     0
27     0
28     0
29     0
      ..
670    0
671    0
672    1
673    0
674    0
675    0
676    0
677    1
678    0
679    1
680    0
681    1
682    0
683    0
684    0
685    0
686    1
687    0
688    0
689    0
690    0
691    0
692    1
693    1
694    0
695    1
696    1
697    1
698    0
699    0
Length: 700, dtype: uint8

In [56]:
reason_type1=reason_dummies.loc[:,1:14].max(axis=1)
reason_type2=reason_dummies.loc[:,15:17].max(axis=1)
reason_type3=reason_dummies.loc[:,18:21].max(axis=1)
reason_type4=reason_dummies.loc[:,22:].max(axis=1)

In [58]:
reason_type1

0      0
1      0
2      0
3      1
4      0
5      0
6      0
7      0
8      0
9      0
10     1
11     1
12     1
13     1
14     0
15     1
16     0
17     0
18     1
19     0
20     1
21     1
22     1
23     0
24     0
25     0
26     0
27     0
28     0
29     0
      ..
670    0
671    0
672    1
673    0
674    0
675    0
676    0
677    1
678    0
679    1
680    0
681    1
682    0
683    0
684    0
685    0
686    1
687    0
688    0
689    0
690    0
691    0
692    1
693    1
694    0
695    1
696    1
697    1
698    0
699    0
Length: 700, dtype: uint8

In [78]:
abs_data=pd.concat([abs_data,reason_type1,reason_type2,reason_type3,reason_type4],axis=1)

In [76]:
#abs_data=abs_data.drop([0,1,2,3],axis=1)
#abs_data

In [80]:
abs_data

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,0,1,2,3
0,07/07/2015,289,36,33,239.554,30,1,2,1,4,0,0,0,1
1,14/07/2015,118,13,50,239.554,31,1,1,0,0,0,0,0,0
2,15/07/2015,179,51,38,239.554,31,1,0,0,2,0,0,0,1
3,16/07/2015,279,5,39,239.554,24,1,2,0,4,1,0,0,0
4,23/07/2015,289,36,33,239.554,30,1,2,1,2,0,0,0,1
5,10/07/2015,179,51,38,239.554,31,1,0,0,2,0,0,0,1
6,17/07/2015,361,52,28,239.554,27,1,1,4,8,0,0,0,1
7,24/07/2015,260,50,36,239.554,23,1,4,0,4,0,0,0,1
8,06/07/2015,155,12,34,239.554,25,1,2,0,40,0,0,1,0
9,13/07/2015,235,11,37,239.554,29,3,1,1,8,0,0,0,1
10,20/07/2015,260,50,36,239.554,23,1,4,0,8,1,0,0,0
11,14/07/2015,260,50,36,239.554,23,1,4,0,8,1,0,0,0
12,15/07/2015,260,50,36,239.554,23,1,4,0,8,1,0,0,0
13,15/07/2015,179,51,38,239.554,31,1,0,0,1,1,0,0,0
14,15/07/2015,179,51,38,239.554,31,1,0,0,4,0,0,0,1
15,17/07/2015,246,25,41,239.554,23,1,0,0,8,1,0,0,0
16,17/07/2015,179,51,38,239.554,31,1,0,0,2,0,0,0,1
17,27/07/2015,179,51,38,239.554,31,1,0,0,8,0,0,1,0
18,30/07/2015,189,29,33,239.554,25,1,2,2,8,1,0,0,0
19,05/08/2015,248,25,47,205.917,32,1,2,1,2,0,0,0,1
20,12/08/2015,330,16,28,205.917,25,2,0,0,8,1,0,0,0
21,03/08/2015,179,51,38,205.917,31,1,0,0,1,1,0,0,0
22,10/08/2015,361,52,28,205.917,27,1,1,4,40,1,0,0,0
23,14/08/2015,260,50,36,205.917,23,1,4,0,4,0,0,0,1
24,17/08/2015,289,36,33,205.917,30,1,2,1,8,0,0,1,0
25,24/08/2015,361,52,28,205.917,27,1,1,4,7,0,0,0,1
26,04/08/2015,289,36,33,205.917,30,1,2,1,1,0,0,0,1
27,12/08/2015,157,27,29,205.917,22,1,0,0,4,0,0,0,1
28,19/08/2015,289,36,33,205.917,30,1,2,1,8,0,0,1,0
29,28/08/2015,179,51,38,205.917,31,1,0,0,2,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,24/04/2018,155,12,34,246.288,25,1,2,0,4,0,0,0,1
671,26/04/2018,225,26,28,246.288,24,1,1,2,8,0,0,1,0
672,26/04/2018,118,13,50,246.288,31,1,1,0,2,1,0,0,0
673,27/04/2018,179,26,30,246.288,19,3,0,0,2,0,0,0,1
674,07/05/2018,235,11,37,237.656,29,3,1,1,8,0,0,0,1
675,09/05/2018,225,15,41,237.656,28,4,2,2,3,0,0,1,0
676,09/05/2018,235,16,32,237.656,25,3,0,0,2,0,0,0,1
677,09/05/2018,118,10,37,237.656,28,1,0,0,3,1,0,0,0
678,09/05/2018,235,20,43,237.656,38,1,1,0,8,0,0,0,1
679,10/05/2018,179,26,30,237.656,19,3,0,0,1,1,0,0,0
680,10/05/2018,291,31,40,237.656,25,1,1,1,2,0,0,0,1
681,10/05/2018,225,15,41,237.656,28,4,2,2,8,1,0,0,0
682,11/05/2018,300,26,43,237.656,25,1,2,1,64,0,0,1,0
683,11/05/2018,225,15,41,237.656,28,4,2,2,8,0,0,0,1
684,11/05/2018,179,26,30,237.656,19,3,0,0,2,0,0,0,1
685,14/05/2018,118,13,50,237.656,31,1,1,0,2,0,0,0,1
686,15/05/2018,118,13,50,237.656,31,1,1,0,3,1,0,0,0
687,15/05/2018,118,10,37,237.656,28,1,0,0,1,0,0,0,1
688,15/05/2018,118,13,50,237.656,31,1,1,0,0,0,0,0,0
689,16/05/2018,179,26,30,237.656,19,3,0,0,2,0,0,0,1
690,16/05/2018,378,49,36,237.656,21,1,2,4,0,0,0,0,0
691,18/05/2018,179,22,40,237.656,22,2,2,0,1,0,1,0,0
692,21/05/2018,155,12,34,237.656,25,1,2,0,48,1,0,0,0
693,21/05/2018,235,16,32,237.656,25,3,0,0,8,1,0,0,0
694,23/05/2018,291,31,40,237.656,25,1,1,1,8,0,0,0,1
695,23/05/2018,179,22,40,237.656,22,2,2,0,8,1,0,0,0
696,23/05/2018,225,26,28,237.656,24,1,1,2,3,1,0,0,0
697,24/05/2018,330,16,28,237.656,25,2,0,0,8,1,0,0,0
698,24/05/2018,235,16,32,237.656,25,3,0,0,2,0,0,0,1
699,31/05/2018,291,31,40,237.656,25,1,1,1,2,0,0,0,1

In [82]:
abs_data.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 0, 1, 2, 3],
      dtype=object)

In [84]:
column_names=['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours','reason_type1','reason_type2','reason_type3','reason_type4']

In [86]:
abs_data.columns=column_names

In [88]:
abs_data.head()

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,reason_type1,reason_type2,reason_type3,reason_type4
0,07/07/2015,289,36,33,239.554,30,1,2,1,4,0,0,0,1
1,14/07/2015,118,13,50,239.554,31,1,1,0,0,0,0,0,0
2,15/07/2015,179,51,38,239.554,31,1,0,0,2,0,0,0,1
3,16/07/2015,279,5,39,239.554,24,1,2,0,4,1,0,0,0
4,23/07/2015,289,36,33,239.554,30,1,2,1,2,0,0,0,1

In [98]:
df_concatented= pd.concat([df_no_age,age_dummies],axis=1)

In [99]:
df_concatented.head()

,Date,Transportation Expense,Distance to Work,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,reason_type1,...,39,40,41,43,46,47,48,49,50,58
0,07/07/2015,289,36,239.554,30,1,2,1,4,0,...,0,0,0,0,0,0,0,0,0,0
1,14/07/2015,118,13,239.554,31,1,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,15/07/2015,179,51,239.554,31,1,0,0,2,0,...,0,0,0,0,0,0,0,0,0,0
3,16/07/2015,279,5,239.554,24,1,2,0,4,1,...,1,0,0,0,0,0,0,0,0,0
4,23/07/2015,289,36,239.554,30,1,2,1,2,0,...,0,0,0,0,0,0,0,0,0,0

In [101]:
abs_data.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'reason_type1',
       'reason_type2', 'reason_type3', 'reason_type4'], dtype=object)

In [102]:
reordered_cols=['reason_type1',
       'reason_type2', 'reason_type3', 'reason_type4',
              'Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets','Absenteeism Time in Hours']

In [103]:
abs_data=abs_data[reordered_cols]

In [105]:
abs_data.head()

,reason_type1,reason_type2,reason_type3,reason_type4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,0,0,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,0,0,0,1,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,1,0,0,0,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,0,0,0,1,23/07/2015,289,36,33,239.554,30,1,2,1,2

In [106]:
df_concatented.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'reason_type1',
       'reason_type2', 'reason_type3', 'reason_type4', 28, 29, 30, 31, 32,
       33, 34, 36, 37, 38, 39, 40, 41, 43, 46, 47, 48, 49, 50, 58],
      dtype=object)

In [107]:
reorder_age_df =['Date', 'Transportation Expense', 'Distance to Work',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'reason_type1',
       'reason_type2', 'reason_type3', 'reason_type4', 28, 29, 30, 31, 32,
       33, 34, 36, 37, 38, 39, 40, 41, 43, 46, 47, 48, 49, 50, 58,'Absenteeism Time in Hours']

In [108]:
df_concatented=df_concatented[reorder_age_df]

In [110]:
df_concatented.head()

,Date,Transportation Expense,Distance to Work,Daily Work Load Average,Body Mass Index,Education,Children,Pets,reason_type1,reason_type2,...,40,41,43,46,47,48,49,50,58,Absenteeism Time in Hours
0,07/07/2015,289,36,239.554,30,1,2,1,0,0,...,0,0,0,0,0,0,0,0,0,4
1,14/07/2015,118,13,239.554,31,1,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,15/07/2015,179,51,239.554,31,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
3,16/07/2015,279,5,239.554,24,1,2,0,1,0,...,0,0,0,0,0,0,0,0,0,4
4,23/07/2015,289,36,239.554,30,1,2,1,0,0,...,0,0,0,0,0,0,0,0,0,2

    Create a checkpoint

In [111]:
abs_data_check = abs_data.copy()

In [112]:
abs_data_check.head()

,reason_type1,reason_type2,reason_type3,reason_type4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,0,0,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,0,0,0,1,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,1,0,0,0,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,0,0,0,1,23/07/2015,289,36,33,239.554,30,1,2,1,2

In [115]:
#abs_data_check['Date']
abs_data_check['Date']=pd.to_datetime(abs_data_check['Date'],format='%d/%m/%Y')

In [118]:
type(abs_data_check['Date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [120]:
abs_data_check.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
reason_type1                 700 non-null uint8
reason_type2                 700 non-null uint8
reason_type3                 700 non-null uint8
reason_type4                 700 non-null uint8
Date                         700 non-null datetime64[ns]
Transportation Expense       700 non-null int64
Distance to Work             700 non-null int64
Age                          700 non-null int64
Daily Work Load Average      700 non-null float64
Body Mass Index              700 non-null int64
Education                    700 non-null int64
Children                     700 non-null int64
Pets                         700 non-null int64
Absenteeism Time in Hours    700 non-null int64
dtypes: datetime64[ns](1), float64(1), int64(8), uint8(4)
memory usage: 57.5 KB

In [122]:
month_list=[]

In [124]:
for i in range(abs_data_check.shape[0]):
    month_list.append(abs_data_check['Date'][i].month)

In [127]:
#month_list
abs_data_check['Month']=month_list

In [129]:
#abs_data_check.head()

In [132]:
def day_of_week(date_value):
    return date_value.weekday()

In [133]:
abs_data_check['Day of week']=abs_data_check['Date'].apply(day_of_week)

In [134]:
abs_data_check.head()

,reason_type1,reason_type2,reason_type3,reason_type4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Month,Day of week
0,0,0,0,1,2015-07-07,289,36,33,239.554,30,1,2,1,4,7,1
1,0,0,0,0,2015-07-14,118,13,50,239.554,31,1,1,0,0,7,1
2,0,0,0,1,2015-07-15,179,51,38,239.554,31,1,0,0,2,7,2
3,1,0,0,0,2015-07-16,279,5,39,239.554,24,1,2,0,4,7,3
4,0,0,0,1,2015-07-23,289,36,33,239.554,30,1,2,1,2,7,3

In [136]:
abs_data_check=abs_data_check.drop('Date',axis=1)

In [138]:
abs_data_check.columns.values

array(['reason_type1', 'reason_type2', 'reason_type3', 'reason_type4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Month',
       'Day of week'], dtype=object)

In [139]:
reorder_cols=['reason_type1', 'reason_type2', 'reason_type3', 'reason_type4',
              'Month','Day of week',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours']

In [140]:
abs_data_check=abs_data_check[reorder_cols]

New checkpoint

In [153]:
df_reason_date_mod=abs_data_check.copy()

In [154]:
df_reason_date_mod.head()

,reason_type1,reason_type2,reason_type3,reason_type4,Month,Day of week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,1,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,1,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,1,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,1,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,1,2,1,2

In [155]:
df_reason_date_mod['Education'].value_counts()

1    583
3     73
2     40
4      4
Name: Education, dtype: int64

In [157]:
df_reason_date_mod['Education']=df_reason_date_mod['Education'].map({1:0,2:1,3:1,4:1})

In [159]:
df_reason_date_mod['Education'].value_counts()

0    583
1    117
Name: Education, dtype: int64

    Final Checkpoint

In [161]:
preprocessed_data = df_reason_date_mod.copy()

In [164]:
preprocessed_data.to_csv('C:/Absenteeism_preprocessed.csv',index=None,header=True)